//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAsc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class KundInfo
    {
        public KundInfo()
        {
            this.Bestallningars = new HashSet<Bestallningar>();
        }
   
        public int KID { get; set; }
        [DisplayName("Företagsnamn")]
        public string ForetagsNamn { get; set; }
        public string Adress { get; set; }
    
        public virtual ICollection<Bestallningar> Bestallningars { get; set; }
    }
}
