//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAsc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Status
    {
        public Status()
        {
            this.Fakturors = new HashSet<Fakturor>();
        }
         
        public int StatusID { get; set; }
        [DisplayName("Status")]
        public string Value { get; set; }
    
        public virtual ICollection<Fakturor> Fakturors { get; set; }
    }
}
