//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAsc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Linq;
    using System.Web;
    using System.Data.Entity;
    
    public partial class vPresentation
    {
        [DisplayName("Företagsnamn")]
        public string ForetagsNamn { get; set; }
        public string Adress { get; set; }
         [DisplayName("Faktura ID")]
        public int FID { get; set; }
         [DisplayName("Arbetstimmar")]
        public int ArbetsTimmar { get; set; }
        public System.DateTime Datum { get; set; }
         [DisplayName("Totalbelopp")]
        public decimal SubTotal { get; set; }
         [DisplayName("Arbetsperiod")]
        public System.DateTime ArbetsPeriod { get; set; }
         [DisplayName("Status")]
        public string Value { get; set; }
    }

    //public class AsciEntities : DbContext
    //{
    //    public DbSet<vPresentation> vPresentation{ get; set; }
    //}
}
